version: '3.7'

services:

  app:
    build:
      context: .
      target: base
    container_name: ConsumerWS
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 8003:80

networks:
  default:
